version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:80'
    environment:
      - ENV=development
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    ports:
      - '5500:80'
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    restart: unless-stopped
